name: Data test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_data_checker:
    name: Check data statistics
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
    - name: Checkout data
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }} # <--- THIS FIXES THE CONTEXT

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        python-version: "3.12"

    - name: Install dependencies
      run: |
        uv sync --locked --dev

    - name: Auth with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Pull data
      env:
        GRPC_ENABLE_FORK_SUPPORT: "False"
      run: |
        mkdir -p data/raw data/processed
        uv run dvc pull --remote remote_storage --jobs 1 --force -v

    - name: Preprocess data
      run: |
        uv run python src/blackjack_predictor/data_/preprocessing.py

    - name: Check data statistics & generate report
      run: |
        uv run python src/blackjack_predictor/data_/dataset_statistics.py

    - name: Install Linux graphics dependencies for CML
      run: |
        sudo apt-get update
        sudo apt-get install -y libpixman-1-dev libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

    - name: Setup CML
      uses: iterative/setup-cml@v3

    - name: Comment on PR
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cml comment create report.md --watermark-title="Data Checker"